### ISSUE TITLE
Dependency moved from jcentre()

### ISSUE THREAD

**Issue by georgetsiga** [SupasinTatiyanupanwong/huawei-maps-utils#4]
Good day

We have noted that JCentre was decommissioned in favor of Maven and the library seems like it was not moved to Maven. 

We are getting the below error when we try to sync 

```
![IMG_3082](https://github.com/user-attachments/assets/cb859593-d810-4c8b-87f3-b713d22a84b3)
![IMG_3282](https://github.com/user-attachments/assets/055205d2-c433-4c05-a4d2-9ca34607f49d)
```

Let me know if there is any work around that we can use.

**Comment by SupasinTatiyanupanwong** [comment]
Hi,

Thank you for reporting this.

Can you please try with the fork mentioned at https://github.com/SupasinTatiyanupanwong/huawei-maps-utils/issues/3 for the time being?

I will try to migrate this to MavenCentral ASAP.

Sorry for your inconvenience.

**Comment by SupasinTatiyanupanwong** [comment]
Hi,

Sorry for late response.

I just published the equivalent version of the library to Maven Central. You can see more details [here](https://github.com/SupasinTatiyanupanwong/huawei-maps-utils/releases/tag/huawei-maps-utils%2F1.0.0-alpha03).

Noted that, due to the migration to Maven Central, the groupId and the namespace of this library was changed.

Ideally, you can just simply update the dependency declaration and update the import statements.

I will try to keep this library in sync with the official one next.

Thanks!

**Comment by georgetsiga** [comment]
Hi Supasin

I will make the changes and let you know.
